---
title: "Codes for re-analysis of differential expression of circular and linear RNAs using Circtest"
output: html_document
date: "2024-01-11"
---

## Loading required libraries

```{r}
library(CircTest)
library(ggplot2)
library(dplyr)
library(rmarkdown)
library(markdown)
library(readxl)
```

# Analysis
## Functions

Function to prepare the data in format to be inputted to CircTest
```{r}
prepare_data <- function(data_file, controls, samples){
  data <- read.table(data_file, header = T)
  data$id <- paste(data$Chr, ":", data$Start, "|", data$End, sep = "")
  data$id <- make.unique(data$id, sep = "_")
  ind_control <- unlist(lapply(controls, function(x) grep(x, colnames(data))))
  ind_sample <- unlist(lapply(samples, function(x) grep(x, colnames(data))))
  data <- data[,c(ncol(data), ind_control, ind_sample)]
  colnames(data) <- c("ID", "Control_1", "Control_2", "Control_3", "Sample_1", "Sample_2", "Sample_3")
  return(data)
}
```

Function for CircTest calling
```{r}
call_circtest <- function(circrnacount, linearcount){
  # # Add pseudocounts to count dataframes
  ind <- which(sapply(circrnacount, is.integer))
  circrnacount[ind] <- circrnacount[ind] + 1
  linearcount[ind] <- linearcount[ind] + 1
  # filtering counts
  Circ_filtered <- Circ.filter(circ = circrnacount, linear = linearcount, Nreplicates = 3, filter.sample = 3, filter.count = 5, percentage = 0.01, circle_description = 1)
  Linear_filtered <- linearcount[rownames(Circ_filtered),]
  # circtest command
  circtest_result <- Circ.test(Circ_filtered, Linear_filtered, group=c(rep(1,3),rep(2,3)), circle_description = 1, alpha = 1)
}
```

## Circtest
Read the file with metadata for circtests
```{r eval=FALSE}
metadata <- read_xlsx("circtest_sample_metadata.xlsx")
```

Calling function for each sample and getting the dataframe
```{r eval=FALSE}
list_data_circle <- list()   # list that stores all data objects that will be used for circtest and deseq2
list_data_linear <- list()
list_circtest <- list()
for (i in 1:nrow(metadata)){
  # forming file, control and sample names
  circcount_file <- metadata$CircRNACount[i]
  linearcount_file <- metadata$LinearRNACount[i]
  control_names <- strsplit(metadata$Control[i], ";")[[1]]
  sample_names <- strsplit(metadata$Sample[i], ";")[[1]]
  print(paste(i, metadata$Data[i], metadata$Experiment[i])) #, circcount_file, linearcount_file))
  # calling function for preparing the data
  circrnacount <- prepare_data(circcount_file, control_names, sample_names)
  linearcount <- prepare_data(linearcount_file, control_names, sample_names)
  list_data_circle[[paste(metadata$Data[i], metadata$Experiment[i], sep = "__")]] <- circrnacount
  list_data_linear[[paste(metadata$Data[i], metadata$Experiment[i], sep = "__")]] <- linearcount
  # calling function for circtest 
  res_circtest <- call_circtest(circrnacount, linearcount)
  list_circtest[[paste(metadata$Data[i], metadata$Experiment[i], sep = "__")]] <- res_circtest
}
```

Printing number of circles passed the criteria and significant circles
```{r}
for (each_id in names(list_circtest)){
  print(paste(each_id, nrow(list_circtest[[each_id]]$summary_table), nrow(list_circtest[[each_id]]$summary_table[list_circtest[[each_id]]$summary_table$sig_p < 0.05,])))
}
```

## DESeq2